### ISSUE TITLE
Duplicate project list for single student in a class

### ISSUE THREAD

**Issue by cstone1** [castiron/vocat#174]
//redacted//

**Comment by cstone1** [comment]
This glitch is now appearing in this class as well http://baruch.vocat.io/courses/650/users/evaluations

It also occurred in the jumbo class referenced in Issue #212 (http://baruch.vocat.io/courses/648/users/evaluations), but seems to have been fixed when you fixed the checkmark issue.

**Comment by zdavis** [comment]
I'm sure it's related. I'll take a look today and will work on a permanent solution.

**Comment by cstone1** [comment]
Thanks!

**Comment by cstone1** [comment]
Hi Zach,

Any update on the duplicate listing issue in course 650 (http://baruch.vocat.io/courses/650/users/evaluations)? The professor is getting frustrated and just emailed saying that she can see that some students have uploaded, but when she clicks into the project from the evaluation grid she frequently gets the "Add Media to Submission" message that you get when there is nothing uploaded. I'm assuming this is related and that it's displaying the version of the duplicated project that doesn't have a video in it.

Best,
Craig

**Comment by cstone1** [comment]
Just got some more clarification from the professor, and a bigger issue is that some projects show a checkmark and a thumbnail but no media is available when you click into it. One example is Mohsin Tariq's "S&E 2 (in-class)" post which shows a thumbnail on one of the two times that project is listed (and shows a checkmark in the evaluation grid) but there's no media visible when you click in through either the student's portfolio or the evaluation grid. I'm trying to figure out if there's a workaround so the professor can view these videos and am not finding anything.

**Comment by zdavis** [comment]
Sorry Craig.. we are so swamped right now! I will look at it in just a few minutes and sort it out.

**Comment by zdavis** [comment]
Craig, it should be fixed for #650 now. I'll need a few days to develop a long term fix for this. There's a race condition that I need to address, and the fix won't be trivial, but I'll get it done.

**Comment by cstone1** [comment]
Thanks! Do you know if it's something we're doing in setting up courses or projects that's triggering it or is it just random?
