### ISSUE TITLE
Logins on App

### ISSUE THREAD

**Issue by cstone1** [castiron/vocat#210]
Hi Zach,

I think the move to the new Active Directory forest has created some confusion with logging in via the App. It doesn't seem to be a problem if you've already logged in, but if you ever log out you get asked for a Domain, and whether I put in ACAD (the old domain) or BC (new one) it gives me a "Check Vocat Domain" error message. Is the Domain field necessary with the new AD forest?

Also related, can the login be Username instead of Email? Email is confusing for students since that is a different account than their AD username.

Best,
Craig

**Comment by cstone1** [comment]
Just got another email about this issue. It seems like anyone who is not already logged in to the app cannot log in, so no new users can use it.

**Comment by cstone1** [comment]
Hi Zach, it's in the iOS app not the web version 
![img_0887](https://user-images.githubusercontent.com/3766552/32340462-0e2c29cc-bfd1-11e7-9efd-26e238ecc115.PNG)

**Comment by zdavis** [comment]
Ahhh... ok. I have an idea for a fix. Gimme a few min.

**Comment by cstone1** [comment]
Works for me now. Thanks!

**Comment by zdavis** [comment]
Good. Sorry about that. The domain field on the app has nothing to do with the LDAP domains. The app looks at a file (vocat.io/vocat_installations.json) to determine what options to show in there. When we rolled over to the new vocat.io site, we failed to copy over that file. I've restored it, and it should work as expected now.
