### ISSUE TITLE
Firefox and Chrome giving "not secure" error

### ISSUE THREAD

**Issue by cstone1** [castiron/vocat#211]
A professor just emailed me saying Firefox won't let them log in at baruch.vocat.io because it gives a "connection is not secure" error (image attached).

Is this something as simple as the Baruch and Vocat logos being http instead of https, or is it something to do with the actual login form?

<img width="1306" alt="screen shot 2017-10-26 at 8 58 38 am" src="https://user-images.githubusercontent.com/3766552/32060918-36798ce6-ba3e-11e7-8e5f-05850bb64916.png">

**Comment by zdavis** [comment]
The SSL certificate had expired. I have installed an updated SSL certificate. This should solve the problem, but let me know if it doesn't.
