### ISSUE TITLE
Checkmarks not showing up for all students who have submitted media

### ISSUE THREAD

**Issue by cstone1** [castiron/vocat#212]
Hey CIC team,

Several students have uploaded videos in course #648 but the checkmarks denoting that they've submitted media are not showing up in the Individual Work grid. http://baruch.vocat.io/courses/648/users/evaluations

Arlene Otero embedded a YouTube video, Jelica Rupar uploaded a MOV, and Hector Paez uploaded an MP4 but none of them have checkmarks.

![screen shot 2017-11-08 at 2 59 40 pm](https://user-images.githubusercontent.com/3766552/32571881-f4d73db6-c496-11e7-8a32-4db1668c81ea.png)
![screen shot 2017-11-08 at 2 59 51 pm](https://user-images.githubusercontent.com/3766552/32571888-f66afc30-c496-11e7-8473-28d7a44e29aa.png)

And of course this professor is particularly prickly about Vocat already. Can you take a look when you get a chance?

Best,
Craig

**Comment by zdavis** [comment]
Thanks Craig. We'll take a look today/tomorrow.

**Comment by SMaxOwok** [comment]
Hey Craig, I started looking into this today.  It's not yet resolved, but we'll continue digging into it tomorrow.  Thanks for your patience.

**Comment by zdavis** [comment]
Craig,

This should be fixed for this course. I don't think we've had a course with this many students, and there seems to be a race condition here that I couldn't see before. I've implemented an interim fix for this course, but need to do some additional work to ensure this doesn't happen again.
