### ISSUE TITLE
Several students are getting Amazon S3 upload error via browser

### ISSUE THREAD

**Issue by cstone1** [castiron/vocat#215]
// redacted //

**Comment by zdavis** [comment]
@SMaxOwok Setup a test course on prod and see if you can reproduce.

**Comment by SMaxOwok** [comment]
@cstone1 do you have any more information about the files that were uploaded?  I was able to upload a .mov and .mp4 to a test course on the production site.

Thanks

**Comment by cstone1** [comment]
The three classes I've heard from students are:

http://baruch.vocat.io/courses/630/groups/evaluations
-Xuejing Yang attempted to upload 335MB .mov file. Ended up doing YouTube embed instead.

http://baruch.vocat.io/courses/650/users/evaluations
- Michael Rifkin got the error. No other info (was reported to me by professor).

http://baruch.vocat.io/courses/625/users/evaluations
-Jiarui Shao, no other info (will find out more when she has access to the file later)

**Comment by zdavis** [comment]
We tried hard to reproduce this and as are of yet unable to do so.

**Comment by cstone1** [comment]
I got another note from a student saying they got the error yesterday evening. It was a 594 MB .mov file but she shared it with me via Google Drive and I was able to upload it no problem. Would they get this error if their connection sucks and the upload never completes? The WiFi here has been awful lately.

**Comment by zdavis** [comment]
Yes, if their upstream connection is bad, then the upload could certainly fail.

**Comment by cstone1** [comment]
One student reported that they stopped getting this error after clearing all cookies.
