### ISSUE TITLE
Can't create a new semester after latest update

### ISSUE THREAD

**Issue by cstone1** [castiron/vocat#216]
Hey CIC team,

I just went to create a couple Spring 2018 sections that were requested early and noticed that I can't make any new semesters now that the course creation menu has a semester dropdown instead of text fields. Is there a way that we can add new semesters? (And should that be limited to Admins?)

Best,
Craig

**Comment by zdavis** [comment]
Hi Craig,

You should be able to make a new semester here: http://manage.vocat.io/semesters

It looks like the ability for organization admins to create a new semester is missing. Only superadmins can do it currently. We'll make a change to remedy this.

Zach

**Comment by cstone1** [comment]
Thanks, Zach. When I'm creating the semesters do I need to bump the positions of all the other semesters or is it totally OK to use 0 and -1 positions to have them show up at the top of the dropdown? (If I put a taken position it returns an error.)

**Comment by zdavis** [comment]
This interface leaves a little to be desired. Let me take a look. What semester are you trying to create?

**Comment by cstone1** [comment]
I created Winter 2018 and put it in 0 figuring that'd just bump everything down, but then when I created Spring 2018 and tried to put it at 0 it told me I couldn't, so I set it to -1.

**Comment by zdavis** [comment]
It's important that they be in the correct order — let me set this up and then we'll improve it so it's easier.

**Comment by zdavis** [comment]
Ok, you should be able to create courses for these semesters. I've asked Max to circle back to this and make it easier to work with.

**Comment by cstone1** [comment]
Thanks!
